[package]
name = "privazy_test"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v5.2.0-nightly.20260815", directory="aztec" }
privazy_contract = { path = "../privazy_contract" }
